language: python
python:
#  - "2.6"
  - "2.7"
 # - "3.2"
  #- "3.3"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq -y swig
  - pip install coveralls
  - pip install .
# command to run tests
script: 
  - nosetests
  - coverage run --source=gender_guess nosetests
after_success:
  coveralls
